// <auto-generated />
using APIRelacionamento.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIRelacionamento.Migrations
{
    [DbContext(typeof(SistemaConsultasDBContext))]
    partial class SistemaConsultasDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("APIRelacionamento.Models.ColaboradorModel", b =>
                {
                    b.Property<int>("idColaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idColaborador"), 1L, 1);

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("salario")
                        .HasColumnType("real");

                    b.HasKey("idColaborador");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("APIRelacionamento.Models.DependenteModel", b =>
                {
                    b.Property<int>("idDependente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDependente"), 1L, 1);

                    b.Property<int>("idColaborador")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idDependente");

                    b.HasIndex("idColaborador");

                    b.ToTable("Dependentes");
                });

            modelBuilder.Entity("APIRelacionamento.Models.DependenteModel", b =>
                {
                    b.HasOne("APIRelacionamento.Models.ColaboradorModel", "Colaborador")
                        .WithMany("ListaDependentes")
                        .HasForeignKey("idColaborador");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("APIRelacionamento.Models.ColaboradorModel", b =>
                {
                    b.Navigation("ListaDependentes");
                });
#pragma warning restore 612, 618
        }
    }
}
